spring:
  profiles: development
  jpa:
    database: MYSQL
    properties:
      hibernate:
        default-schema: intCount
        dialect : org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://mysql:3306/intCount
    platform: mysql
    username: root
    password:
    initialization-mode: never
  application:
    name: store-service
management:
  security.enabled: false
  port: 40008
server:
  port: 8080
logging.level.org.springframework.security: DEBUG
